import { DefaultLayout } from "@/components";
import {
  Card,
  CardBody,
  CardFooter,
  Heading,
  Stack,
  Text,
  Image,
} from "@chakra-ui/react";
import Head from "next/head";
// import Image from "next/image";

export interface GroupCardProps {
  name: string;
  category: string;
  imgSrc: string;
  overview: string;
  members: number;
}

const dummyData: GroupCardProps = {
  name: "배철수의 음악캠프",
  category: "음악",
  imgSrc: "/groupTestImg.webp",
  overview: "배철수의 음악캠프를 사랑하는 사람 모두 모여라!!",
  members: 1557,
};

const index = () => {
  return (
    <div>
      <Head>
        <title>Join Us - GroupList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Card
          direction={{ base: "column", sm: "row" }}
          overflow="hidden"
          variant="outline"
        >
          <Image
            objectFit="cover"
            maxW={{ base: "100%", sm: "200px" }}
            src={dummyData.imgSrc}
            alt="Caffe Latte"
          />

          <Stack>
            <CardBody>
              <Heading size="md">The perfect latte</Heading>

              <Text py="2">
                Caffè latte is a coffee beverage of Italian origin made with
                espresso and steamed milk.
              </Text>
            </CardBody>

            <CardFooter></CardFooter>
          </Stack>
        </Card>
      </DefaultLayout>
    </div>
  );
};

export default index;
