import { useGetGroup } from "@/apis/group";
import { DefaultLayout } from "@/components";
import { GroupDescription, GroupNav } from "@/containers";
import { GroupBanner } from "@/containers/group";
import { DynamicRender } from "@/containers/group/DynamicRender";
import { Group } from "@/types";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export const dummyGroupData: Group = {
  imgSrc: "/none-groupimg.webp",
  name: "음악속으로",
  categories: ["음악"],
  description: "안녕하세요! 음악을 좋아하는 사람들의 모임입니다.",
  minimum_age: 0,
  maximum_age: 100,
  capacity: 10,
  sex: true,
};

const GroupDetail = () => {
  const router = useRouter();
  const { data: group, isSuccess } = useGetGroup(Number(router.query.id));
  const [navItem, setNavItem] = useState("Home");
  const [onCreateFeed, setOnCreateFeed] = useState(false);

  return (
    <>
      <Head>
        <title>Join Us - GroupDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        {isSuccess && (
          <Flex direction={"column"} w={"100%"} minH={1400}>
            <GroupBanner />
            <GroupDescription group={group} />
            <GroupNav
              setSelected={setNavItem}
              selected={navItem}
              setOnCreateFeed={setOnCreateFeed}
              onCreateFeed={onCreateFeed}
            />
            <DynamicRender
              selected={navItem}
              group={group}
              onCreateFeed={onCreateFeed}
            />
          </Flex>
        )}
      </DefaultLayout>
    </>
  );
};

export default GroupDetail;
