import { useFetch } from "@/apis";
import { ApiRoutes } from "@/constants";
import { GroupDetail } from "@/containers";
import { FeedWithPage } from "@/types";
import { toUrl } from "@/utils";
import Head from "next/head";
import { useRouter } from "next/router";

const Notice = () => {
  //현재 미구현이라서 임시로 Feed로 대체했습니다.
  const router = useRouter();
  const numberingQueryId = Number(router.query.id);
  const { data: feeds, isSuccess } = useFetch<FeedWithPage>(
    toUrl(ApiRoutes.GroupFeed, { id: numberingQueryId })
  );

  return (
    <>
      <Head>
        <title>Join Us - Group Notice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GroupDetail>
        {/* {isSuccess && feeds && <GroupFeed feeds={feeds.data} />} */}
      </GroupDetail>
    </>
  );
};

export default Notice;
