import React, { useEffect } from "react";
import FileUpload from "@/components/common/FileUpload";
import { FiFile } from "react-icons/fi";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Box,
  Button,
  Heading,
  Image,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import { DefaultLayout } from "@/components";
import { useQuery } from "@tanstack/react-query";
import { getUserInfo } from "@/apis/auth";
import userStore from "@/stores/userInfo";

type Props = {};

const MyPage = (props: Props) => {
  const { userName } = userStore();
  // imageUpload
  const validateFiles = (value: FileList) => {
    if (value.length < 1) {
      return "Files is required";
    }
    for (const file of Array.from(value)) {
      const fsMb = file.size / (1024 * 1024);
      const MAX_FILE_SIZE = 10;
      if (fsMb > MAX_FILE_SIZE) {
        return "Max file size 10mb";
      }
    }
    return true;
  };

  // "https://kr.object.ncloudstorage.com/joinus/image/profile.png"

  return (
    <>
      <Head>
        <title>Join Us - myPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Box ml={8} mt={2}>
          <Heading as="h1" size="md">
            프로필 수정
          </Heading>
          <Text mt={2} fontSize="sm">
            프로필 사진과 이름을 변경할 수 있습니다.
          </Text>
        </Box>

        <Box ml={8} mt={6} display={"flex"}>
          <Text>프로필 사진</Text>
          <Image
            mt={4}
            ml={10}
            borderRadius="full"
            boxSize="120px"
            src="https://bit.ly/dan-abramov"
            alt="Dan Abramov"
          />
        </Box>

        <Box ml={8} mt={6}>
          <Button>사진 변경</Button>
          <Button>삭제</Button>
          <Button>버튼</Button>
        </Box>

        <Box ml={8} mt={10}>
          <Text>별명</Text>
        </Box>
        <Button mt={8}>적용</Button>
      </DefaultLayout>
    </>
  );
};

export default MyPage;
