import { toCheckToken } from "@/apis";
import { DefaultLayout } from "@/components";
import UpdateUserForm from "@/containers/auth/mypage/updateUserForm";
import { Box, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

type Props = {};

const MyPage = (props: Props) => {
  const router = useRouter();

  useEffect(() => {
    const hasToken = toCheckToken();
    if (!hasToken) {
      router.push("/");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Join Us - myPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Box ml={44} mt={2}>
          <Heading as="h1" size="md">
            프로필 수정
          </Heading>
          <Text mt={2} fontSize="sm">
            프로필 사진과 이름을 변경할 수 있습니다.
          </Text>
        </Box>
        <UpdateUserForm />
      </DefaultLayout>
    </>
  );
};

export default MyPage;
