import { CreateFeed, GroupDetail } from "@/containers";
import Head from "next/head";

const Create = () => {
  return (
    <>
      <Head>
        <title>Join Us - Create Feed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GroupDetail>
        <CreateFeed />
      </GroupDetail>
    </>
  );
};

export default Create;
