import { useGetGroupFeeds } from "@/apis";
import { WindowVirtualList } from "@/components/common/DynamicInfiniteList";
import { GroupDetail, GroupFeedItem } from "@/containers";
import { Feed } from "@/types";
import { QueryParser } from "@/utils";
import Head from "next/head";
import { useRouter } from "next/router";

const FeedPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Join Us - Feeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GroupDetail>
        <WindowVirtualList<Feed>
          infiniteQueryResult={useGetGroupFeeds({
            clubId: QueryParser.toNumber(router.query.id),
            limit: 10,
          })}
          renderItem={GroupFeedItem}
          gap={"4"}
          emptyDataMessage="작성된 피드가 없습니다. 첫번째로 작성을 해보세요!"
        />
      </GroupDetail>
    </>
  );
};

export default FeedPage;
