import { DefaultLayout } from "@/components";
import { SetGroup, SetGroupOptions } from "@/containers";
import { Group } from "@/types/group";
import { Container, Flex, Heading } from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";

const CreateGroup = () => {
  const initialGroupState: Group = {
    name: "",
    category: "",
    description: "",
    Age: [0, 100],
    maxParticipants: 10,
  };
  const [group, setGroup] = useState<Group>(initialGroupState);

  return (
    <>
      <Head>
        <title>Join Us - CreateGroup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex gap={12} mt={12} mb={20}>
          <Container>123</Container>
          <Container>
            <SetGroup setGroup={setGroup} group={group} />
            <SetGroupOptions setGroup={setGroup} group={group} />
          </Container>
        </Flex>
      </DefaultLayout>
    </>
  );
};

export default CreateGroup;
