import { getGroupList } from "@/apis";
import { DefaultLayout } from "@/components";
import { GroupCard } from "@/containers";
import { GroupCardProps } from "@/containers/group/GroupCard/GroupCard";
import { Text } from "@chakra-ui/react";
import { useQuery } from "@tanstack/react-query";
import Head from "next/head";

const dummyData: GroupCardProps = {
  id: 1,
  name: "배철수의 음악캠프",
  category: "음악",
  imgSrc: "/groupTestImg.webp",
  overview: "배철수의 음악캠프를 사랑하는 사람 모두 모여라!!",
  members: 1557,
};

const GroupList = () => {
  const { data } = useQuery({
    queryKey: ["group-list"],
    queryFn: () => getGroupList(),
  });
  console.log(data);
  return (
    <div>
      <Head>
        <title>Join Us - GroupList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Text as="b" fontSize="xl" mt={5}>
          이런 모임 어때요?
        </Text>
        <GroupCard groupData={dummyData} />
      </DefaultLayout>
    </div>
  );
};

export default GroupList;
