import { DefaultLayout } from "@/components";
import { Button } from "@chakra-ui/react";
import Head from "next/head";

import { useMutation } from "@tanstack/react-query";

export default function Home() {
  const { mutate } = useMutation({
    mutationFn: () => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          reject("hello");
        }, 1000);
      });
    },
    onSuccess: (data) => {
      console.log("success2");
    },
  });

  return (
    <>
      <Head>
        <title>Join Us - Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Button onClick={() => mutate()}>Hello, World</Button>
        <Button variant={"ghost"}>Hello, World</Button>
        <Button variant={"outline"}>Hello, World</Button>
      </DefaultLayout>
    </>
  );
}
