import { DefaultLayout } from "@/components";
import { Button, Flex } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Join Us - Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
        <Flex>A 브랜치</Flex>
      </DefaultLayout>
    </>
  );
}
