import { DefaultLayout } from "@/components";
import { SetGroup, SetGroupOptions } from "@/containers";
import { Group } from "@/types/group";
import { Heading } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";

const CreateGroup = () => {
  const [group, setGroup] = useState<Group>({
    name: "",
    category: "",
    description: "",
    Age: [0, 100],
    maxParticipants: 10,
  });

  useEffect(() => {
    console.log(group);
  }, [group]);

  return (
    <>
      <Head>
        <title>Join Us - CreateGroup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Heading w="100%" textAlign={"center"} fontWeight="normal" mb="2%">
          그룹을 만들어보세요.
        </Heading>
        <SetGroup setGroup={setGroup} group={group} />
        {/** 그룹명,카테고리,그룹소개 */}
        <SetGroupOptions setGroup={setGroup} group={group} />
        {/** 연령제한,최대인원,성별제한 */}
      </DefaultLayout>
    </>
  );
};

export default CreateGroup;
