import { useGetUser } from "@/apis";
import { DefaultLayout } from "@/components";
import { UserCard, UserGroup } from "@/containers";
import { QueryParser } from "@/utils";
import { Box, Flex } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const UserDetail = () => {
  const router = useRouter();
  const userId = QueryParser.toNumber(router.query.id);
  const { data: userData } = useGetUser(userId);

  return (
    <>
      <Head>
        <title>Join Us - UserDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex
          w={{ base: "100%", md: "container.md" }}
          py={12}
          direction={"column"}
          gap={14}
        >
          {userData && <UserCard data={userData} />}
          {userData && <UserGroup user={userData} />}
        </Flex>
      </DefaultLayout>
    </>
  );
};

export default UserDetail;
