import { useGetUser } from "@/apis";
import { DefaultLayout } from "@/components";
import { UserCard } from "@/containers";
import { QueryParser } from "@/utils";
import { Box } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const UserDetail = () => {
  const router = useRouter();
  const userId = QueryParser.toNumber(router.query.id);
  const { data: userData } = useGetUser(userId);
  return (
    <>
      <Head>
        <title>Join Us - UserDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Box w={{ base: "100%", md: "container.md" }} py={12}>
          {userData && <UserCard data={userData} />}
        </Box>
      </DefaultLayout>
    </>
  );
};

export default UserDetail;
