import { DefaultLayout } from "@/components";
import { UpdateUserForm } from "@/containers";
import { Box, Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";

const UserDetail = () => {
  return (
    <>
      <Head>
        <title>Join Us - UserDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex
          direction={"column"}
          w={{ base: "100%", md: "container.md" }}
          bgColor={"yellow.100"}
          gap={4}
        >
          <Heading as="h1" size="md">
            프로필 수정
          </Heading>
          <Text fontSize="sm">프로필 사진과 이름을 변경할 수 있습니다.</Text>

          <UpdateUserForm />
        </Flex>
      </DefaultLayout>
    </>
  );
};

export default UserDetail;
