import { GroupMember } from "@/containers";
import { GroupDetail } from "@/containers";
import Head from "next/head";

const Member = () => {
  return (
    <>
      <Head>
        <title>Join Us - Group Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GroupDetail>
        <GroupMember />
      </GroupDetail>
    </>
  );
};

export default Member;
