import { Feed, useGetFeeds } from "@/apis";
import { DefaultLayout } from "@/components";
import { WindowVirtualList } from "@/components/common/DynamicInfiniteList";
import { NewFeedItem } from "@/containers";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";

const NewFeed = () => {
  return (
    <>
      <Head>
        <title>Join Us - NewFeed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Flex w={"100%"} direction={"column"} pt={8} pb={8} gap={8}>
          <WindowVirtualList<Feed>
            infiniteQueryResult={useGetFeeds({ limit: 10 })}
            renderItem={NewFeedItem}
            emptyDataMessage="작성된 피드가 없습니다. 첫번째로 작성을 해보세요!"
          />
        </Flex>
      </DefaultLayout>
    </>
  );
};
export default NewFeed;
